version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8003:8003"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3307:3307"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: unicode123
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "8003:8003"
        networks: 
            - laravel